title: Contact
author: Emma
description:
 Sweet and simple blog to document my coding journey

# social links
twitter_username: ewainy # DO NOT include the @ character, or else the build will fail!
github_username:  ewainy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
